[package]
name = "hoplite_verb_chooser"
version = "0.1.1"
edition = "2021"

[dependencies]
#hoplite_verbs_rs = { path = "../hoplite_verbs_rs" }
hoplite_verbs_rs = { git = "https://github.com/jeremymarch/hoplite_verbs_rs", version = "0.5.1" }
rand = "0.8.5"
